-- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/131124?language=oracle

SELECT MP.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM (
    SELECT MEMBER_ID, DENSE_RANK() OVER(ORDER BY COUNT(*) DESC) DRNO
    FROM REST_REVIEW
    GROUP BY MEMBER_ID) X
, MEMBER_PROFILE MP 
, REST_REVIEW R 
WHERE DRNO = 1
AND MP.MEMBER_ID = X.MEMBER_ID
AND R.MEMBER_ID = X.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;


-- Gimini 최적화 (Top N 알고리즘 사용 가능)
SELECT  MP.MEMBER_NAME, 
        R.REVIEW_TEXT, 
        TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW R ON MP.MEMBER_ID = R.MEMBER_ID
WHERE MP.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    FETCH FIRST 1 ROWS WITH TIES
)
ORDER BY REVIEW_DATE, R.REVIEW_TEXT;