-- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/131537?language=oracle

SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE >= TO_DATE('20220301', 'YYYYMMDD')
AND SALES_DATE < TO_DATE('20220401', 'YYYYMMDD')
UNION ALL
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD'), PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE >= TO_DATE('20220301', 'YYYYMMDD')
AND SALES_DATE < TO_DATE('20220401', 'YYYYMMDD')
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID