-- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/144856?language=oracle

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, X.CATEGORY, X.TOTAL_SALES
FROM (
        SELECT B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE * BS.SALES) TOTAL_SALES
        FROM BOOK_SALES BS
        INNER JOIN BOOK B
        ON B.BOOK_ID = BS.BOOK_ID
        WHERE BS.SALES_DATE >= TO_DATE('2022-01-01', 'YYYY-MM-DD')
        AND BS.SALES_DATE < TO_DATE('2022-02-01', 'YYYY-MM-DD')
        GROUP BY B.AUTHOR_ID, B.CATEGORY
) X 
INNER JOIN AUTHOR A 
ON A.AUTHOR_ID = X.AUTHOR_ID 
ORDER BY X.AUTHOR_ID, X.CATEGORY DESC