-- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/132204?language=oracle

SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A, PATIENT P, DOCTOR D
WHERE P.PT_NO = A.PT_NO 
AND D.DR_ID = A.MDDR_ID
AND TO_CHAR(A.APNT_YMD, 'YYYYMMDD') = '20220413'
AND A.APNT_CNCL_YN = 'N'
AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD;