-- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/157341?language=oracle

SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
WHERE C.CAR_TYPE = '세단'
AND CH.CAR_ID = C.CAR_ID
AND CH.START_DATE >= TO_DATE('20221001', 'YYYYMMDD')
AND CH.START_DATE < TO_DATE('20221101', 'YYYYMMDD')
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;