-- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/164668?language=oracle

SELECT U.USER_ID, U.NICKNAME, TOTAL_SALES
FROM (
    SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES 
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) B, USED_GOODS_USER U 
WHERE U.USER_ID = B.WRITER_ID
ORDER BY TOTAL_SALES;