-- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/133027?language=oracle

SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) SUM_TOTAL_ORDER
    FROM (
        SELECT FLAVOR, TOTAL_ORDER
        FROM FIRST_HALF
        UNION ALL 
        SELECT FLAVOR, TOTAL_ORDER
        FROM JULY
    )
    GROUP BY FLAVOR
    ORDER BY SUM(TOTAL_ORDER) DESC
)
WHERE ROWNUM < 4;

SELECT FLAVOR
FROM (
    SELECT FLAVOR, TOTAL_ORDER
    FROM FIRST_HALF
    UNION ALL 
    SELECT FLAVOR, TOTAL_ORDER
    FROM JULY
)
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
FETCH FIRST 3 ROWS ONLY;

