-- 출처 : https://school.programmers.co.kr/learn/courses/30/lessons/144855?language=oracle

SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B, BOOK_SALES S 
WHERE S.BOOK_ID = B.BOOK_ID
AND S.SALES_DATE >= TO_DATE('20220101', 'YYYYMMDD')
AND S.SALES_DATE < TO_DATE('20220201', 'YYYYMMDD')
GROUP BY B.CATEGORY 
ORDER BY B.CATEGORY;